### ISSUE TITLE
T76677 Gltf Imports are splitted into chunks

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1069]
https://developer.blender.org/T76677

**Comment by scurest** [comment]
It's expected that meshes get split into chunks with continuous UVs/normals/tangents/colors of course. The obvious question is why the exporter splits the sides into individual quads though, since the normal should be constant on each side

![Sides](https://user-images.githubusercontent.com/11024420/81959965-ddcd1880-95d5-11ea-8caa-5204280d5ad3.png)

The reason is tiny differences in the calculated normals. If the normal is rounded off (say with `round(x, 6)` in `extract_primitives`) you'll get this

![With rounding](https://user-images.githubusercontent.com/11024420/81960137-1a007900-95d6-11ea-9e82-229f45fefbe0.png)

master also splits based on tangents even though tangents aren't exported by default. That's fixed by #1023.

**Comment by scurest** [comment]
Do you think the importer should merge verts together that differ only in their UVs/normals/tangents/colors?

**Comment by emackey** [comment]
> Do you think the importer should merge verts together that differ only in their UVs/normals/tangents/colors?

It wouldn't hurt.  There's been a lot of user confusion over why glTF does it this way, and perhaps the importer could hide all that by automatically merging the vertices.  Done correctly, it wouldn't affect the roundtrip tests, which would split apart again on export.

**Comment by scurest** [comment]
I blocked out a prototype for the importer: [weld-verts-experiment](https://github.com/KhronosGroup/glTF-Blender-IO/compare/master...scurest:weld-verts-experiment).  
It's far enough along to play around with.

Here's an example with CesiumMan. The branch manages to import it all as one piece.

![out](https://user-images.githubusercontent.com/11024420/82514050-40447e00-9ada-11ea-8180-2f4cc1359822.png)

Perf looks between 1.2-2.5x slower so far (only tested with small models).

**Comment by scurest** [comment]
So about the merging verts experiment...

I think it's basically done. I got the import time down to around 0.9-1.5x master's import time (by throwing tons caches at it lol).

### Blender->glTF->Blender

The Blender->glTF->Blender roundtrip works. Originially-distinct-but-collocated verts can get merged obviously.

### glTF->Blender->glTF

But the glTF->Blender->glTF roundtrip is... ehhh. The vertex count can sometimes increase or decrease.

I don't know why it would decrease, but the reason for increasing is the custom per-loop normals (ie. vertex-per-face normals). When you set normals with `normals_split_custom_set`, you do not necessarily get the exact same normals back out when you read them out again. So the importer can give the same normal at two loops, but when the exporter reads them out, they can be different, and so it will obviously split that vert, increasing the vert count. Rounding the normal off like I said in the first comment can help but its not enough because the difference can be appreciable.

Here's an example with 01_vertex_count_32bit. The vert in the center of blue edges (those are sharp; `normals_split_custom_set` marks them sharp automatically) had the same normal at all its loops when passed into `normals_split_custom_set`, but the actual resulting normals are visibly different.

![out](https://user-images.githubusercontent.com/11024420/82696626-02a43a00-9c2d-11ea-9e58-0d73ffbbf786.png)

Blender stores some complicated internal representation of custom per-loop normals ([see, uhhh, this](https://github.com/sobotka/blender/blob/d8a3f3595af0fb3ca5937e41c2728fd750d986ef/source/blender/blenkernel/intern/mesh_evaluate.c#L1736-L1744)) which is why I guess this happens. And its totally down to using `normals_split_custom_set` (which takes a normal per loop) instead of `normals_split_custom_set_from_vertices` (which takes one per vertex) like master. If master is changed to set the exact same normals but using `normals_split_custom_set`, it has the same behavior.

So yeah, Blender seems to be able to set and read back custom normals when setting one per vert, but it doesn't do it reliably if you set one per loop, which makes merging verts not work very well.

**Comment by emackey** [comment]
I'm impressed by the sleuthing and the handwritten Unicode table flip.

Does the situation improve if the normals are submitted per-vertex, and then "merge by distance" is called as a post-process step?  Or does the data all end up in the same place anyway, making this unavoidable?

We don't need to stay married to tests that demand glTF->Blender->glTF perfection in terms of vertex count.  But we should make sure that this type of change is worth it to end users, as it looks like there's a speed penalty.

**Comment by scurest** [comment]
The reason I didn't is because we don't want to merge just by distance. That would merge collocated verts with distinct vertex groups (bone weights) for example. But if we did do that, the per loop normals don't seem to work out either.

Obviously the situation pictured above (01_vertex_count_32bit) wouldn't happen, since, like I said, everything is okay if you set per-vertex normals, and in this case no merging is happening so the merge-by-distance wouldn't do anything.

But if we look at 10_custom_normals: if you import (using master) and then run merge-by-distance, it does not produce the correct per-loop normals

![out](https://user-images.githubusercontent.com/11024420/86610324-ce81a000-bf72-11ea-9cb0-5a9f29c75622.png)

**Comment by julienduroure** [comment]
I merged the initial bug fix.
Keeping this issue alive because of normals discussion on it

**Comment by scurest** [comment]
Let me record two more problems with setting per-loop normals.

-----

There's a method `mesh.validate()` that deletes degenerate/duplicate/OOB tris and their loops. This is pretty important because Blender will crash if you give it bad tris.

It also seems to clear the custom normals (you can tell it not to but it doesn't appear to fix up the custom data to match the fixed-up mesh, which also causes crashing).

That means we need to set the per-loop normals _after_ `mesh.validate()`. So we have a list of normals for each loop, right? But `mesh.validate()` has deleted some random loops to fixup bad geometry and we have no idea which were deleted. Out list of normals is now bad. If we try to set the normals and some loops were deleted or something, we get an exception.

With per-vert normals, this isn't a problem, because `mesh.validate()` doesn't delete verts.

-----

The second problem: consider a mesh like this. It has two coincident tris and six verts (three collocated pairs). The tris have opposite normals. This would be the normal way to create a "double-sided" face when backface culling is turned on for example.

![twotris](https://user-images.githubusercontent.com/11024420/87519734-a1ef1780-c647-11ea-89b8-fcb56dede005.png)

Now if we dedupe these verts, we get just three verts, and two duplicate tris (ie. two tris on the same set of three verts). Blender actually appears to be okay with the duplicate tris. But we have to call `mesh.validate()` (because there might be degenerate tris or something and Blender isn't okay with that) and `mesh.validate()` deletes the duplicate tri, turning this into a "one-sided" face.

**Comment by scurest** [comment]
@julienduroure @emackey How about we close this? The model from T76677 now imports as expected when using "Merge Vertices" and "Flat Shading". I think it will be easier to track anything further with specific issues.

**Comment by emackey** [comment]
Thanks @scurest!
