### ISSUE TITLE
`Emission` materials not exporting, throwing Traceback

### ISSUE THREAD

**Issue by dsinni** [KhronosGroup/glTF-Blender-IO#111]
I've been testing the IO exporter with certain materials/shaders, and I've run into issues with the `Emission` shader.

I'm using the latest Blender 2.8 Beta and have tried the following node configurations with no luck:

![image](https://user-images.githubusercontent.com/4733018/49248565-05332400-f3e8-11e8-8de8-d348114deb41.png)

![image](https://user-images.githubusercontent.com/4733018/49248591-17ad5d80-f3e8-11e8-9c17-61e73b794f0b.png)

![image](https://user-images.githubusercontent.com/4733018/49248868-bdf96300-f3e8-11e8-9755-eeb36da27fc7.png)

Errors:
![image](https://user-images.githubusercontent.com/4733018/49248739-6c50d880-f3e8-11e8-8311-9414f2bb0f27.png)

I'm relatively new to material/shader node configurations in Blender, but from what I've seen, I was under the impression that at least one of the above would work with the IO exporter. If not, please let me know what I'm doing wrong so I can test properly.

Thanks and keep up the great work!

**Comment by UX3D-nopper** [comment]
Fixed here: https://github.com/KhronosGroup/glTF-Blender-IO/commit/50654eaf0cb62889cab711762f1b5355f2776b1c

Following node setup export is now working again:
![image](https://user-images.githubusercontent.com/27856744/49285370-885f8300-f497-11e8-8e9a-e5775cdc9ee1.png)

**Comment by dsinni** [comment]
Thanks, @UX3D-nopper! I'll give it a go in the next build.

**Comment by julienduroure** [comment]
Is now merge with Blender repo, will be available next build

**Comment by dsinni** [comment]
I just tried this in the latest Blender 2.8 Beta `0f5b53ba4dc` build and still having issues using all of the above node configurations.

![image](https://user-images.githubusercontent.com/4733018/49330958-26b91a80-f564-11e8-8b59-19b9b8d4dcc8.png)

![image](https://user-images.githubusercontent.com/4733018/49330955-13a64a80-f564-11e8-9c4b-c823b66f08ed.png)

**Comment by julienduroure** [comment]
This had been merged with blender repo this morning, this is not available yet in build of Nov. 30th.
It will be available in next build, probably tomorrow morning

**Comment by dsinni** [comment]
I just tried with the latest build from Dec. 3rd, using @UX3D-nopper's node configuration. No export error this time so that's good, but the glTF validator is throwing an error: 

`ARRAY_LENGTH_NOT_IN_LIST | Invalid array length 4. Valid lengths are: (3). | /materials/0/emissiveFactor`

Node configuration:
![image](https://user-images.githubusercontent.com/4733018/49348136-a254bd80-f671-11e8-94f0-c68393486594.png)

Note that the material is affected by light; I'm not sure if that is the intended result. Should emissive materials still be affected by light in this way?

With lights applied:
![image](https://user-images.githubusercontent.com/4733018/49348381-104db480-f673-11e8-80a0-dcdd53fcbc00.png)

Without lights applied:
![image](https://user-images.githubusercontent.com/4733018/49348404-35dabe00-f673-11e8-9706-74d1ac3092cd.png)

Blender version:
![image](https://user-images.githubusercontent.com/4733018/49348548-109a7f80-f674-11e8-900e-2602fe79480f.png)

**Comment by donmccurdy** [comment]
If you make the base color black it won’t be affected by lights. Otherwise emissive is added to the normal PBR output. Same should be true in Blender I think. Think of it as a PBR material that also emits (some) light.

**Comment by dsinni** [comment]
Ah, that does make sense. I think I was just used to using the `glTF Metallic Roughness` PBR nodes, and I don't remember that being a requirement there.

The validator error still does seem to be an issue, however.

`ARRAY_LENGTH_N`OT_IN_LIST | Invalid array length 4. Valid lengths are: (3). | /materials/0/emissiveFactor

**Comment by julienduroure** [comment]
Is now merged with blender 2.8 repo

**Comment by dsinni** [comment]
I'm not sure if this is the correct place for this, but I think it is worth noting that, currently, even if you disconnect the `Principled BSDF` shader, Blender 2.8 or the exporter still seems to include it, presumably on export.

Disconnected with `Roughness: 0`:
![image](https://user-images.githubusercontent.com/4733018/49466228-8403d480-f7cd-11e8-86c4-5985bd264ea8.png)

Gloss:
![image](https://user-images.githubusercontent.com/4733018/49466308-bc0b1780-f7cd-11e8-9071-5f8bd3910c72.png)

Disconnected with `Roughness: 1`:
![image](https://user-images.githubusercontent.com/4733018/49466713-bd890f80-f7ce-11e8-8449-20bb3f733507.png)

Matte:
![image](https://user-images.githubusercontent.com/4733018/49466761-dd203800-f7ce-11e8-9403-f876d914344f.png)

If the `Principled BSDF` shader's `Base Color` is a color other than black, the results are more obvious.

I've been noticing a bit of node/shader weirdness in the Blender Beta, so not sure which is responsible in this case.

**Comment by dsinni** [comment]
Thanks for that info, @emackey!

> So, the exporter attempts to analyze your node graph, to figure out what textures and what values are to be placed in the glTF material. The glTF importer will construct a new Blender node graph from scratch based on the values in the glTF material.

I think I follow for the most part, but does that mean that in the exporter's analysis of the node graph, it doesn't necessarily discern between connected and disconnected nodes?

What I find odd is that the settings from the `Principled` shader are being used even if it's not connected to the rest of the graph, rather than defaulting to whatever the glTF default is, if there is one. Is that intentional?

> The Blender Principled BSDF node accepts separate, grayscale values for roughness and metallic values. So when the importer finds a glTF ORM texture, it automatically creates a "Separate RGB" node, such that it can pull roughness out of the green channel, and metallic out of the blue channel, and send them into the Principled node individually.

Interesting. So does that mean that `Separate RGB` should not appear in the node graph at all since it is automatic?

Will the ORM texture still need to be produced with image editing software as it did with the previous `glTF Metallic Roughness` PBR nodes, or is there another way to handle that now?

>  We're still working on what to do about the Occlusion map (red channel), as there's no hookup for it on the Principled node.

Ah, okay. I _was_ wondering how that would be handled.

**Comment by emackey** [comment]
> does that mean that in the exporter's analysis of the node graph, it doesn't necessarily discern between connected and disconnected nodes?

It follows links where it needs to, for example to detect which image nodes are connected to which sockets on the Principled node.  But I doubt it pays much attention to whether the Principled node itself is plugged into an output or not.  That's something that could potentially be fixed, but, is that a common use case for Blender artists, to leave such a dangling node there?

> So does that mean that `Separate RGB` should not appear in the node graph at all since it is automatic? Or were you referring specifically to the importer?

I meant the importer, specifically, places that node there on import, otherwise Blender can't understand the contents of the glTF ORM texture.  I believe the exporter will kind of reverse-engineer the node hookups there to see which channel is being sourced from where.

But the exporter should also be willing to take for example a pair of grayscale images, separately connected (one to roughness, and one to metallic), and blend them together into a combined image for glTF.  This case wouldn't require a special node, because the exporter is well aware of how glTF specifies its textures to be packed.

**Comment by donmccurdy** [comment]
> That's something that could potentially be fixed, but, is that a common use case for Blender artists, to leave such a dangling node there?

Not high priority, but I would vote for fixing this eventually — can definitely imagine an artist wanting to create both unlit and PBR versions of an asset for different devices, and swapping a node socket seems like a very reasonable way to do that.

**Comment by dsinni** [comment]
Thanks, @emackey! 

So, just for clarification:

- A `Separate RGB` node should _not_ be needed in order to export Metallic/Roughness.
- Using an image editor such as GIMP or Photoshop should no longer be required to combine the RGB of the ORM texture as this will be done automatically by the exporter.

Is this correct?

In addition to @donmccurdy's point, users may also keep around a few different variations of the shader(s) with different settings disconnected in the same node graph. I sometimes do this when I find a combination I like, but still want to experiment, so it may not be all that extraordinary.

It's possible that the connected shader would completely override the disconnected; I haven't tested that yet, but I'd imagine it's better to rule it out by limiting to what is actually connected.
