### ISSUE TITLE
Alpha is ignored, unless it comes from the same source as BaseColor

### ISSUE THREAD

**Issue by j-conrad** [KhronosGroup/glTF-Blender-IO#1417]
**Describe the bug**
This is almost identical to https://github.com/KhronosGroup/glTF-Blender-IO/issues/1219. Except this still occurs when using a Background node (for exporting an Unlit shader).

**To Reproduce**

1. Create a plane
2. Assign a Background node in its shader graph (unlit shader).
3. Plug an image texture node (with a PNG containing transparency) from the the Color output to the Color input of the Background node.
4. Plug an image texture node (with a PNG containing transparency) from the Alpha output to the Strength input of the Background node.
5. Export as .glb and view in any glTF viewer.
6. RESULT: The alpha is exported.
7. Now go back and plug ANY OTHER image (or no image) into the BaseColor input of the Background node.
8. Re-export as .glb and view in any glTF viewer.
9. RESULT: The alpha does not show.

**Expected behavior**
Alpha should get exported regardless of the BaseColor network.

**Screenshots**
This works as expected. (Alpha is exported)
![image](https://user-images.githubusercontent.com/31968496/121977385-c01f3500-cd3a-11eb-9aaf-ca54b49a1cfd.png)

This does not work. (Alpha appears to be ignored)
![image](https://user-images.githubusercontent.com/31968496/121977431-e0e78a80-cd3a-11eb-82a8-ece8c4e0bdc7.png)

**.blend file/ .gltf**
Attached

**Version**
 - OS: Windows
 - Blender Version 2.93.0

**Additional context**

[AlphaBackgroundIssue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6652049/AlphaBackgroundIssue.zip)

**Comment by julienduroure** [comment]
Confirmed.
This is a known limitation.
Cf comment in code :
![image](https://user-images.githubusercontent.com/1696020/122091791-794c4080-ce09-11eb-97bc-b40189ae8e1f.png)

**Comment by scurest** [comment]
Note that that's not the correct setup for alpha, so it wouldn't work even if the above comment were fixed. Background Strength has nothing to do with alpha and is always ignored. The right setup is (I assume this is what you want the cube to look like)

![alpha](https://user-images.githubusercontent.com/11024420/122161190-e3c7a580-ce36-11eb-95b6-8d4d102ad5c7.jpg)

**Comment by j-conrad** [comment]
> Note that that's not the correct setup for alpha, so it wouldn't work even if the above comment were fixed. Background Strength has nothing to do with alpha and is always ignored. The right setup is (I assume this is what you want the cube to look like)

Ok. Looks like I missed that in the Blender docs. Any idea why it works then? (My first example graph gives the same exact result as your image above.)

**Comment by j-conrad** [comment]
I figured it out. I was misunderstanding how that Mix Shader was working, as well as how that Transparent BSDF works.

The behavior I was seeing makes sense. By swapping those Shader inputs, I was effectively changing which one was being affected by the Factor's alpha texture. That, combined with a complex alpha texture, was making it seem more complicated that it actually was.

I still don't quite understand why my first example works though.

**Comment by j-conrad** [comment]
Ugh...  the plot thickens. I should have actually tested your example, @scurest. If you export as you have demonstrated above, that object does have alpha, but the object is just white instead of having the color of the texture that's being input in the lower Shader node. I'm officially very confused again.

**Comment by j-conrad** [comment]
Something's definitely not quite right, or at least not what the Blender glTF documentation would have me believe.

I replaced the image texture with alpha with a different one I had lying around.

![image](https://user-images.githubusercontent.com/31968496/122280258-df82a300-ce9d-11eb-8fe4-4d66e7e0f89e.png)


And the result of the export:
![image](https://user-images.githubusercontent.com/31968496/122280371-faedae00-ce9d-11eb-9b84-6c2b65b80c6f.png)


I cannot fathom why the COLOR of that texture with Alpha is being exported at all. Its color output is NOT plugged into anything, only its ALPHA.

This could be a larger bug.

**Comment by scurest** [comment]
Yes, the comment julienduroure posted obviously still applies.

> Note that that's not the correct setup for alpha, so it wouldn't work **even if the above comment were fixed**

**Comment by aelainelong** [comment]
> I cannot fathom why the COLOR of that texture with Alpha is being exported at all. Its color output is NOT plugged into anything, only its ALPHA.
> 
> The original description of this issue still stands then. It's assuming the color comes from the same source as the alpha, no matter what is mixed into the Mix Shader node.

Same exact issue I've run into recently. @julienduroure Any thoughts on how difficult this would be to remedy? Or if a fix is even possible given the code comment above?
