### ISSUE TITLE
Shape Key/Morph Target Animations Not Working As Expected

### ISSUE THREAD

**Issue by dizziless** [KhronosGroup/glTF-Blender-IO#1932]
Hi there, I'm back!

Same model as before, this time with two facial animations (Smile and Blink) that are each driven by their own shape key.

Their 0 and 1 values were keyframed into their own Action and Pushed Down to create their own NLA track.

Blink was made first, Smile second.

Smile plays exactly as expected in Don's viewer, but playing Blink somehow activates the Smile shape key at what seems to be 50% strength. It doesn't play both at the same time, it just makes the character smile while blinking instead of only blinking.

What's causing the problem here?

https://github.com/KhronosGroup/glTF-Blender-IO/assets/130783670/495c2011-4d45-4e30-abea-c20853c9476f

I realize you might need to see either the blend file or the glb to diagnose the problem, but I don't actually have the legal right to share it. If StellarGame allows it, I will share as soon as I get his response. There's quite a big timezone difference between him and myself so it will only be later in the day (for me) when I receive his response.

If there is anything you can think of or suggest before needing to see the files, I would greatly appreciate hearing it.

**Comment by julienduroure** [comment]
Hello,
As you said, difficult to say anything without having a look at the blend file.
But I suspect that the all shapekeys are not all keyed in each animation, so it leads to same issue than for TRS animation, that was solved here:
https://github.com/KhronosGroup/glTF-Blender-IO/commit/78dcd88a4109206315103a2ed3be9f0d8bb15aa5

**Comment by dizziless** [comment]
Forgive me, but I don't really understand code and I don't know what TRS animation is, but you are correct that not all shape keys are keyed in each animation. Each animation only has one shape key being keyframed. The problem is that the Blink animation is somehow also activating the shape key that is used to keyframe the Smile animation (the Smile shape key).

Are you saying this is fixed in one of the latest versions of blender? We are using a customized version of the exporter in blender 3.2.1 that allows us to export face maps. By any chance, is that feature also available in any of the latest versions of blender? If so, then it seems like the best thing to do is just update blender.

**Comment by julienduroure** [comment]
This comment was some information about my investigations. This is not solved yet.

Face maps are not available in any version of the exporter. Face Maps may be removed from Blender, starting Blender 4.0.
See https://projects.blender.org/blender/blender/issues/105317

**Comment by StellarGame** [comment]
@julienduroure , thanks for the quick reply and information regarding this bug as well as additional info about the evolution of face map support in blender.

Based on your responses I have two questions:

1. Am I understanding correctly that this bug is slated to be fixed in the 4.0 exporter release?

2. Is there a way to make multiple shape key animations work without this interference in the meantime? I'm not sure if we can key all shape keys and what that would entail, but you seem to be alluding that if we had done that we would not be seeing the interference between animations?

**Comment by julienduroure** [comment]
> Am I understanding correctly that this bug is slated to be fixed in the 4.0 exporter release?

Yes. 

> Is there a way to make multiple shape key animations work without this interference in the meantime? I'm not sure if we can key all shape keys and what that would entail, but you seem to be alluding that if we had done that we would not be seeing the interference between animations?

Yes, you are right. You can add a keyframe for each keys. It should solve your issue

**Comment by dizziless** [comment]
> > Am I understanding correctly that this bug is slated to be fixed in the 4.0 exporter release?
> 
> Yes.
> 
> > Is there a way to make multiple shape key animations work without this interference in the meantime? I'm not sure if we can key all shape keys and what that would entail, but you seem to be alluding that if we had done that we would not be seeing the interference between animations?
> 
> Yes, you are right. You can add a keyframe for each keys. It should solve your issue

Just a single keyframe for each key? One keyframe is technically not an animation, so I'm assuming that the Action that is created as a result of creating the keyframe should not be Pushed Down as an NLA Track? And lastly (I think/hope), should these keyframes all be created in a single Action or should each be made a Fake User and unlinked so the next one can have its own Action?

**Comment by julienduroure** [comment]
> One keyframe is technically not an animation

This is not true. Adding a keyframe creates an animation in Blender.

Only 1 action is created, with N channels if the mesh has N shapekeys, so in your case, no new action needs to be created. You only need to be sure to have N channels in your action, if the mesh has N shapekeys
