### ISSUE TITLE
Duplicates of linked collection not exported.

### ISSUE THREAD

**Issue by roxlu** [KhronosGroup/glTF-Blender-IO#500]
**Describe the bug**
When you create a collection in `A.blend`, then create `B.blend` and link this collection, then create a duplicate of the instance, the duplicated instance is not exported. 

**To Reproduce**
See _describe the bug_

**Expected behavior**
Each instance should be exported as node in GLTF.

**Version**
 - OS: Arch Linux 5.1.4
 - Blender Version: 2.8, 2019-05-25 

**Additional context**
Might be relevant: https://github.com/KhronosGroup/glTF-Blender-IO/issues/484

**Comment by roxlu** [comment]
For anyone who runs into this issue, I found a workaround for the time being. 1) Exprort to FBX, then use 2) https://github.com/facebookincubator/FBX2glTF

**Comment by julienduroure** [comment]
I started to have a look on it.
Some thoughts about it (for myself, to not forgot)

* instances are used for dupli instance and for linking instances
* Need to invalidate the cache to get a new node, to avoid having same node multiple time in scene tree
* Have to check how it will work for armature instances (proxy)
* Check that nodes are not in scene root
* instance offset seems to not work as expected

**Comment by roxlu** [comment]
Thanks @julienduroure awesome you're looking into this. 

I dove into Blender/Python a bit and got a very simplistic exporter working that fits my needs. I'm sure everything in that code is familiar to you, but maybe there are some parts that might be interesting. Especially because it works with linked files/collections/etc. 

https://gist.github.com/roxlu/a3ec74d3e214526c026bdc06adc24117#file-exporter-py-L848

**Comment by kmturley** [comment]
I am getting the same issue.

monkeys.blend contains one Monkey head, with two instances using Blender Collection Instances:
https://docs.blender.org/manual/en/latest/scene_layout/object/properties/instancing/collection.html
<img width="910" alt="Screen Shot 2020-02-28 at 4 33 05 PM" src="https://user-images.githubusercontent.com/1710493/75597034-0d916900-5a48-11ea-94d8-73c7023655ab.png">

Exported directly to gltf format only one shows:
<img width="615" alt="Screen Shot 2020-02-28 at 4 32 03 PM" src="https://user-images.githubusercontent.com/1710493/75597105-5ba66c80-5a48-11ea-8b0f-e10ab44f435b.png">
monkeys-blender.gltf 2KB
monkeys-blender.bin 69KB

meshes:
```
{
    "name" : "Suzanne.004",
    "primitives" : [
        {
            "attributes" : {
                "POSITION" : 0,
                "NORMAL" : 1,
                "TEXCOORD_0" : 2
            },
            "indices" : 3
        }
    ]
}
```

nodes:
```
{
    "mesh" : 0,
    "name" : "Suzanne"
},
{
    "children" : [
        0
    ],
    "name" : "Duplication_Offset_Monkeys2"
},
{
    "name" : "Duplication_Offset_Monkeys3"
}
```

However export to FBX, and then to GLTF using: https://github.com/facebookincubator/FBX2glTF
<img width="844" alt="Screen Shot 2020-02-28 at 4 32 15 PM" src="https://user-images.githubusercontent.com/1710493/75597125-75e04a80-5a48-11ea-8f23-8c1e5e5d74c0.png">
monkeys-fbx.gltf 8KB
monkeys-fbx.bin 137KB

meshes:
```
{
    "name": "Suzanne",
    "primitives": [
        {
            "material": 0,
            "mode": 4,
            "attributes": {
                "NORMAL": 2,
                "POSITION": 1,
                "TEXCOORD_0": 3
            },
            "indices": 0
        }
    ]
},
{
    "name": "Monkeys3|Suzanne.001|Dupli|",
    "primitives": [
        {
            "material": 0,
            "mode": 4,
            "attributes": {
                "NORMAL": 6,
                "POSITION": 5,
                "TEXCOORD_0": 7
            },
            "indices": 4
        }
    ]
}
```

nodes:
```
{
    "name": "RootNode",
    "translation": [
        0.0,
        0.0,
        0.0
    ],
    "rotation": [
        0.0,
        0.0,
        0.0,
        1.0
    ],
    "scale": [
        1.0,
        1.0,
        1.0
    ],
    "children": [
        1,
        2,
        4
    ]
},
{
    "name": "Suzanne",
    "translation": [
        0.0,
        0.0,
        0.0
    ],
    "rotation": [
        -0.707106828689575,
        0.0,
        0.0,
        0.707106709480286
    ],
    "scale": [
        100.0,
        100.0,
        100.0
    ],
    "mesh": 0
},
{
    "name": "Monkeys2",
    "translation": [
        0.0,
        0.0,
        -3.93487048149109
    ],
    "rotation": [
        -0.707106828689575,
        0.0,
        0.0,
        0.707106709480286
    ],
    "scale": [
        100.0,
        100.0,
        100.0
    ],
    "children": [
        3
    ]
},
{
    "name": "Monkeys2|Suzanne|Dupli|",
    "translation": [
        0.0,
        0.0,
        0.0
    ],
    "rotation": [
        -1.32348898008484e-23,
        -0.0,
        0.0,
        1.0
    ],
    "scale": [
        1.0,
        1.0,
        1.0
    ],
    "mesh": 0
},
{
    "name": "Monkeys3",
    "translation": [
        -3.78579711914062,
        0.0,
        0.200917467474937
    ],
    "rotation": [
        -0.707106828689575,
        0.0,
        0.0,
        0.707106709480286
    ],
    "scale": [
        100.0,
        100.0,
        100.0
    ],
    "children": [
        5
    ]
},
{
    "name": "Monkeys3|Suzanne.001|Dupli|",
    "translation": [
        0.0,
        0.0,
        0.0
    ],
    "rotation": [
        -1.32348898008484e-23,
        -0.0,
        0.0,
        1.0
    ],
    "scale": [
        1.0,
        1.0,
        1.0
    ],
    "mesh": 1
}
```

This feature is essential for creating small compressed 3D models for the web. It results in smaller Network requests which is helpful especially for Mobile devices..

**Comment by julienduroure** [comment]
@kmturley This is solved by PR #950.
Target is to merge it soon (and will be available in blender 2.83)

**Comment by StidOfficial** [comment]
Thanks, he work for me but he don't work if you have A link to B and link to C.

**Comment by julienduroure** [comment]
@StidOfficial I opened  #1049 to track this subject

**Comment by LorenzWieseke** [comment]
For me it still isnt working in version 1.5.1 of the addon.
When I link in a collection and export everything works fine, if I duplicate that collection the gltf viewer gives me the following errors 
![image](https://user-images.githubusercontent.com/29607121/97702746-c7494980-1aaf-11eb-8421-fb8e96379fd1.png)

I exported with "selected objects" turned off.
![image](https://user-images.githubusercontent.com/29607121/97702794-dfb96400-1aaf-11eb-99fd-6805981e4ecd.png)

Only workaround for me is to use make library override form relations menu (not Outliner, that does nothing)
