### ISSUE TITLE
Exporting Multiple Scenes

### ISSUE THREAD

**Issue by TimoBuskeKdab** [KhronosGroup/glTF-Blender-IO#972]
**Describe the bug**
If I have multiple scenes in my Blender file (each containing objects), it will fail to export gltf.

**To Reproduce**
Pick one:
A: Create a second scene and add 1 object to each scene, then export gltf.
B: Link two external Blender files, each containing objects, then export gltf.
C: Append two external Blender files, each containing objects, then export gltf.

**Expected behavior**
It should be one gltf written containing multiple scenes.

**Screenshots**

**.blend file/ .gltf**
http://www.timobuske.de/misc/blender-merged.zip

**Version**
 - Windows 10
 - Blender 2.81

**Additional context**

**Comment by julienduroure** [comment]
Hello,
Using 2.82 + current master of this addon:

A: Seems to work, I can see 2 scenes in gltf export
![image](https://user-images.githubusercontent.com/1696020/76566769-c1b1db80-64ad-11ea-88f9-9c730ac7b85a.png)

B: What did you link exactly ? Scenes ? Is this the attached example ? 
This will be solved by #950 

C: Seems to work, I can see 3 scenes in gltf export (my empty scene + 2 appended scenes
![image](https://user-images.githubusercontent.com/1696020/76567230-a398ab00-64ae-11ea-886d-d2c078371d7b.png)

**Comment by donmccurdy** [comment]
When I tried to export this I got a runtime error:

![Screen Shot 2020-03-12 at 9 02 14 AM](https://user-images.githubusercontent.com/1848368/76571090-ec7f3e00-6473-11ea-93ce-dc4da51097cd.png)

... but I had an older version of Blender 2.81 beta here. Maybe it's fixed in 2.82?

**Comment by julienduroure** [comment]
@donmccurdy Did you try to export the merged.blend from attachment? IIUC, this is the point B.
This will be fixed in PR #950

**Comment by TimoBuskeKdab** [comment]
Hi, indeed with Blender 2.82 using current master it seems not crashing linking scenes.
Thx.

**Comment by TimoBuskeKdab** [comment]
Hmm... For complex scenes still getting a crash for case B and C using latest Blender 2.82 + master.
Maybe I can try to reduce the scenes it to the minimum...

`'C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\python\lib\site-packages\extern_draco.dll' exists, draco mesh compression is available
07:48:58 | INFO: Starting glTF 2.0 export
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\__init__.py", line 502, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 41, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 54, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 63, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 37, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 56, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(blender_object, blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 47, in gather_node
    node = __gather_node(blender_object, blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 61, in __gather_node
    children=__gather_children(blender_object, blender_scene, export_settings),
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 130, in __gather_children
    node = gather_node(child_object, blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 47, in gather_node
    node = __gather_node(blender_object, blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 61, in __gather_node
    children=__gather_children(blender_object, blender_scene, export_settings),
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 130, in __gather_children
    node = gather_node(child_object, blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 47, in gather_node
    node = __gather_node(blender_object, blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 61, in __gather_node
    children=__gather_children(blender_object, blender_scene, export_settings),
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 130, in __gather_children
    node = gather_node(child_object, blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 47, in gather_node
    node = __gather_node(blender_object, blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 65, in __gather_node
    mesh=__gather_mesh(blender_object, export_settings),
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 321, in __gather_mesh
    export_settings)
  File "C:\Program Files\Blender Foundation\Blender-282-ewdemo\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 48, in wrapper_cached
    cache_key += (i.name,)
ReferenceError: StructRNA of type Mesh has been removed`

**Comment by julienduroure** [comment]
Are you sure that you are using the last master of this addon ?
This error should be fixed already

**Comment by donmccurdy** [comment]
> Did you try to export the merged.blend from attachment?

I had tested `merged.blend` in 2.81 beta, yes.

**Comment by julienduroure** [comment]
This ticket is quite old, and the original test case is no more available.
I'm going to close it.
If you still have some issue, please create a new ticket!
